logo:
  use_default: true
govcmsui_use_bootstrap: 1
govcmsui_use_jquery: 1
govcmsui_coa: coas-stacked.svg
govcmsui_coa_footer: 1
govcmsui_navbar_justified: 1
govcmsui_use_fontawesome: 1
govcmsui_footer_copyright: 'Commonwealth of Australia'
_core:
  default_config_hash: 2nt9_O-P6HFE89GUFU3agd6eltjEI3YO8Kc_JrZszW8
